-- GENERATED from data/enums/animation.yaml. Do not edit.
xi = xi or {}

---@enum xi.animation
xi.animation =
{
    NONE                   = 0,
    ATTACK                 = 1,
    DESPAWN                = 2,
    DEATH                  = 3,
    EVENT                  = 4,
    CHOCOBO                = 5,
    FISHING                = 6,
    OPEN_DOOR              = 8,
    CLOSE_DOOR             = 9,
    ELEVATOR_UP            = 10,
    ELEVATOR_DOWN          = 11,
    FISHING_NPC            = 32,
    HEALING                = 33,
    FISHING_FISH           = 38,
    FISHING_CAUGHT         = 39,
    FISHING_ROD_BREAK      = 40,
    FISHING_LINE_BREAK     = 41,
    FISHING_MONSTER        = 42,
    FISHING_STOP           = 43,
    SYNTH                  = 44,
    SIT                    = 47,
    RANGED                 = 48,
    FISHING_START          = 50,
    NEW_FISHING_START      = 56,
    NEW_FISHING_FISH       = 57,
    NEW_FISHING_CAUGHT     = 58,
    NEW_FISHING_ROD_BREAK  = 59,
    NEW_FISHING_LINE_BREAK = 60,
    NEW_FISHING_MONSTER    = 61,
    NEW_FISHING_STOP       = 62,
    SITCHAIR_0             = 63,
    SITCHAIR_1             = 64,
    SITCHAIR_2             = 65,
    SITCHAIR_3             = 66,
    SITCHAIR_4             = 67,
    SITCHAIR_5             = 68,
    SITCHAIR_6             = 69,
    SITCHAIR_7             = 70,
    SITCHAIR_8             = 71,
    SITCHAIR_9             = 72,
    SITCHAIR_10            = 73,
    MOUNT                  = 85,
    TRUST                  = 90,
}
