#!/usr/bin/env python3
"""Generate SQL patch for missing mob_pools and mob_groups poolid fixes from LSB upstream."""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import dbtool
import mariadb

LSB_POOLS = Path(r"C:\Users\Administrator\.cursor\projects\c-PegasusXI-server\lsb-tmp\sql\mob_pools.sql")
LSB_GROUPS = Path(r"C:\Users\Administrator\.cursor\projects\c-PegasusXI-server\lsb-tmp\sql\mob_groups.sql")
OUT = Path(__file__).parent.parent / "sql" / "patches" / "fix_missing_mob_pools_from_lsb.sql"

POOL_INSERT_RE = re.compile(r"^INSERT INTO `mob_pools` VALUES \((\d+),")
GROUP_INSERT_RE = re.compile(
    r"^INSERT INTO `mob_groups` VALUES \((\d+),(\d+),(\d+),'([^']+)'"
)
NAME_MAX_LEN = 32
PACKET_NAME_MAX_LEN = 24


def _truncate_pool_names(sql: str) -> str:
    """mob_pools.name is varchar(32); packet_name is varchar(24) in xidb."""
    prefix = "INSERT INTO `mob_pools` VALUES ("
    if not sql.startswith(prefix):
        return sql
    body = sql[len(prefix) :].rstrip(");")
    parts: list[str] = []
    cur: list[str] = []
    in_str = False
    escape = False
    for ch in body:
        cur.append(ch)
        if escape:
            escape = False
            continue
        if ch == "\\":
            escape = True
            continue
        if ch == "'":
            in_str = not in_str
            continue
        if ch == "," and not in_str:
            parts.append("".join(cur[:-1]))
            cur = []
    parts.append("".join(cur))
    if len(parts) >= 3:
        limits = {1: NAME_MAX_LEN, 2: PACKET_NAME_MAX_LEN}
        for idx, max_len in limits.items():
            val = parts[idx].strip()
            if val.startswith("'") and val.endswith("'"):
                text = val[1:-1].replace("''", "'")
                if len(text) > max_len:
                    text = text[:max_len]
                    parts[idx] = "'" + text.replace("'", "''") + "'"
    return prefix + ",".join(parts) + ") ON DUPLICATE KEY UPDATE poolid=VALUES(poolid);"


def load_lsb_pools(pool_ids: set[int]) -> dict[int, str]:
    found: dict[int, str] = {}
    with LSB_POOLS.open(encoding="utf-8", errors="replace") as f:
        for line in f:
            m = POOL_INSERT_RE.match(line)
            if not m:
                continue
            pid = int(m.group(1))
            if pid in pool_ids:
                raw = line.split("--")[0].strip().rstrip(";")
                found[pid] = _truncate_pool_names(raw)
    return found


def load_lsb_group_poolids() -> dict[tuple[int, int], tuple[int, str]]:
    """Map (zoneid, groupid) -> (poolid, name) from LSB."""
    mapping: dict[tuple[int, int], tuple[int, str]] = {}
    with LSB_GROUPS.open(encoding="utf-8", errors="replace") as f:
        for line in f:
            m = GROUP_INSERT_RE.match(line)
            if not m:
                continue
            groupid, poolid, zoneid, name = int(m.group(1)), int(m.group(2)), int(m.group(3)), m.group(4)
            mapping[(zoneid, groupid)] = (poolid, name)
    return mapping


def main() -> None:
    dbtool.fetch_credentials()
    conn = mariadb.connect(
        host=dbtool.host,
        port=dbtool.port,
        user=dbtool.login,
        passwd=dbtool.password,
        db=dbtool.database,
    )
    cur = conn.cursor()
    cur.execute(
        """
        SELECT DISTINCT g.poolid
        FROM mob_groups g
        LEFT JOIN mob_pools p ON g.poolid = p.poolid
        WHERE p.poolid IS NULL AND g.poolid != 0
        ORDER BY g.poolid
        """
    )
    missing_poolids = {row[0] for row in cur.fetchall()}

    # Also include pools referenced by LSB mob_groups where we have poolid=0 locally
    lsb_groups = load_lsb_group_poolids()
    cur.execute(
        """
        SELECT zoneid, groupid, name, poolid
        FROM mob_groups
        WHERE poolid = 0
        """
    )
    extra_poolids: set[int] = set()
    group_updates: list[tuple[int, int, int, str, int]] = []
    for zoneid, groupid, name, poolid in cur.fetchall():
        key = (zoneid, groupid)
        if key not in lsb_groups:
            continue
        lsb_poolid, lsb_name = lsb_groups[key]
        if lsb_poolid == 0:
            continue
        extra_poolids.add(lsb_poolid)
        group_updates.append((zoneid, groupid, lsb_poolid, name, poolid))

    all_needed = missing_poolids | extra_poolids
    lsb_pools = load_lsb_pools(all_needed)

    lines: list[str] = [
        "-- Sync missing mob_pools rows and mob_groups poolid mappings from LandSandBoat base branch.",
        "-- Generated by tools/gen_lsb_mob_pool_patch.py",
        "",
    ]

    not_in_lsb = sorted(all_needed - set(lsb_pools.keys()))
    if not_in_lsb:
        lines.append(f"-- WARNING: {len(not_in_lsb)} poolids not found in LSB: {not_in_lsb}")
        lines.append("")

    for pid in sorted(lsb_pools.keys()):
        sql = lsb_pools[pid]
        if not sql.endswith(";"):
            sql += ";"
        lines.append(sql)

    lines.append("")
    for zoneid, groupid, lsb_poolid, name, _ in sorted(group_updates):
        lines.append(
            f"UPDATE `mob_groups` SET `poolid` = {lsb_poolid} "
            f"WHERE `zoneid` = {zoneid} AND `groupid` = {groupid} AND `name` = '{name}';"
        )

    # Fix groups that reference missing pools (poolid != 0) using LSB mapping when names match
    cur.execute(
        """
        SELECT g.zoneid, g.groupid, g.name, g.poolid
        FROM mob_groups g
        LEFT JOIN mob_pools p ON g.poolid = p.poolid
        WHERE p.poolid IS NULL AND g.poolid != 0
        ORDER BY g.zoneid, g.groupid
        """
    )
    for zoneid, groupid, name, poolid in cur.fetchall():
        key = (zoneid, groupid)
        if key not in lsb_groups:
            continue
        lsb_poolid, lsb_name = lsb_groups[key]
        if lsb_poolid == poolid:
            continue
        lines.append(
            f"UPDATE `mob_groups` SET `poolid` = {lsb_poolid} "
            f"WHERE `zoneid` = {zoneid} AND `groupid` = {groupid} AND `name` = '{name}';"
        )

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"  missing pool refs: {len(missing_poolids)}")
    print(f"  pool inserts: {len(lsb_pools)}")
    print(f"  group poolid=0 fixes: {len(group_updates)}")
    print(f"  not in LSB: {not_in_lsb}")


if __name__ == "__main__":
    main()
